define profile_share::share (
  $ensure = present,
  $available = '',
  $browsable = '',
  $comment = '',
  $copy = '',
  $create_mask = '',
  $directory_mask = '',
  $force_create_mask = '',
  $force_directory_mode = '',
  $force_group = '',
  $force_user = '',
  $guest_ok = '',
  $guest_only = '',
  $hide_unreadable = '',
  $path = "/srv/shares/${title}",
  $op_locks = '',
  $level2_oplocks = '',
  $veto_oplock_files = '',
  $read_only = '',
  $public = '',
  $read_list = '',
  $write_list = '',
  $writable = '',
  $printable = '',
  $valid_users = '',
  $follow_symlinks = '',
  $wide_links = '',
  $acl_group_control = '',
  $map_acl_inherit = '',
  $profile_acls = '',
  $store_dos_attributes = '',
  $strict_allocate = '',
  $hide_dot_files = '',
  $root_preexec = '',
  $inherit_permissions = '',
  $inherit_acls = '',
  $delete_readonly = '',
  $printer_name = '',
  $msdfs_root = '',
  $guest_account = '',
  $force_delete_dir = false,
) {

  samba::server::share {$title:
    ensure                => $ensure,
    available             => $available,
    browsable             => $browsable,
    comment               => $comment,
    copy                  => $copy,
    create_mask           => $create_mask,
    directory_mask        => $directory_mask,
    force_create_mask     => $force_create_mask,
    force_directory_mode  => $force_directory_mode,
    force_group           => $force_group,
    force_user            => $force_user,
    guest_ok              => $guest_ok,
    guest_only            => $guest_only,
    hide_unreadable       => $hide_unreadable,
    path                  => "/srv/shares/${title}",
    op_locks              => $op_locks,
    level2_oplocks        => $level2_oplocks,
    veto_oplock_files     => $veto_oplock_files,
    read_only             => $read_only,
    public                => $public,
    read_list             => $read_list,
    write_list            => $write_list,
    writable              => $writable,
    printable             => $printable,
    valid_users           => $valid_users,
    follow_symlinks       => $follow_symlinks,
    wide_links            => $wide_links,
    acl_group_control     => $acl_group_control,
    map_acl_inherit       => $map_acl_inherit,
    profile_acls          => $profile_acls,
    store_dos_attributes  => $store_dos_attributes,
    strict_allocate       => $strict_allocate,
    hide_dot_files        => $hide_dot_files,
    root_preexec          => $root_preexec,
    inherit_permissions   => $inherit_permissions,
    inherit_acls          => $inherit_acls,
    delete_readonly       => $delete_readonly,
    printer_name          => $printer_name,
    msdfs_root            => $msdfs_root,
    guest_account         => $guest_account,
  }

  if $ensure != present and $force_delete_dir == true {
    $share_dir_ensure = absent
  } else {
    $share_dir_ensure = directory
  }

  file { "/srv/shares/${title}":
    ensure  => $share_dir_ensure,
    mode    => '0666',
    force   => true,
    owner   => 'nobody',
    group   => 'nobody',
  }

}
